- name: Distribute SSH Key to VMs
  hosts: gepeim
  become: true  # Needed if creating users or modifying root-owned files
  tasks:
    - name: Ensure the .ssh directory exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Ensure correct permissions on authorized_keys
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: file
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
